configure properly with Xenomai
git-svn-id: svn://svn.code.sf.net/p/rtfirewire/code/trunk@47 04546202-7ef8-0310-8fa3-8943173b309c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -275,7 +275,7 @@ PACKAGE_BUGREPORT='rtfirewire-devel@lists.berlios.de'
 
 ac_unique_file="stack/ieee1394_core.c"
 ac_default_prefix=/usr/local/rt-firewire
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS CONFIG_RTAI_TRUE CONFIG_RTAI_FALSE CONFIG_XENO_TRUE CONFIG_XENO_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTFW_TARGET_ARCH RTFW_MODULE_EXT RTFW_KBUILD_ENV RTFW_KBUILD_CMD RTFW_KBUILD_CLEAN RTFW_MODULE_DIR CONFIG_RTFW_LXRT_TRUE CONFIG_RTFW_LXRT_FALSE RTAI_KMOD_CFLAGS RTAI_USER_CFLAGS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT RANLIB ac_ct_RANLIB CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CCAS CCASFLAGS LD CONFIG_NCURSES_TRUE CONFIG_NCURSES_FALSE NCURSES_LIBS CONFIG_RTAI_TRUE CONFIG_RTAI_FALSE CONFIG_XENO_TRUE CONFIG_XENO_FALSE CONFIG_KBUILD_TRUE CONFIG_KBUILD_FALSE RTFW_TARGET_ARCH CROSS_COMPILE RTFW_MODULE_EXT RTFW_KBUILD_ENV RTFW_KBUILD_CMD RTFW_KBUILD_CLEAN RTFW_MODULE_DIR CONFIG_RTFW_LXRT_TRUE CONFIG_RTFW_LXRT_FALSE RTEXT_KMOD_CFLAGS RTEXT_USER_CFLAGS LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3312,7 +3312,7 @@ echo $ECHO_N "checking for Xenomai version... $ECHO_C" >&6
     XENO_VERSION="`${XENO_CONFIG} --version`"
 
     case "$XENO_VERSION" in
-        1.9.9)
+        1.9.9 | 2.*)
             CONFIG_RTFW_RTEXT_VERSION=xeno-2x
 
 cat >>confdefs.h <<\_ACEOF
@@ -3595,24 +3595,29 @@ esac
 
 
 
-# AC_MSG_CHECKING([for CROSS_COMPILE])
-# if test "${CROSS_COMPILE}" = ""; then
-#    CROSS_COMPILE="`echo ${CC} | sed s/gcc//`"
-#
- # if test "${CROSS_COMPILE}gcc" \!= "${CC}"; then
-#	CROSS_COMPILE=""
-#	AC_MSG_RESULT([Cannot identify CROSS_COMPILE - assuming none - set manually if needed])
- # else
-#	if test "${CROSS_COMPILE}" = ""; then
-#		AC_MSG_RESULT([none])
-#	else
-#		AC_MSG_RESULT([${CROSS_COMPILE}])
-#	fi
- #  fi
-# else
-  #  AC_MSG_RESULT([${CROSS_COMPILE}])
-# fi
-# AC_SUBST(CROSS_COMPILE)
+echo "$as_me:$LINENO: checking for CROSS_COMPILE" >&5
+echo $ECHO_N "checking for CROSS_COMPILE... $ECHO_C" >&6
+ if test "${CROSS_COMPILE}" = ""; then
+    CROSS_COMPILE="`echo ${CC} | sed s/gcc//`"
+
+ if test "${CROSS_COMPILE}gcc" \!= "${CC}"; then
+	CROSS_COMPILE=""
+	echo "$as_me:$LINENO: result: Cannot identify CROSS_COMPILE - assuming none - set manually if needed" >&5
+echo "${ECHO_T}Cannot identify CROSS_COMPILE - assuming none - set manually if needed" >&6
+  else
+	if test "${CROSS_COMPILE}" = ""; then
+		echo "$as_me:$LINENO: result: none" >&5
+echo "${ECHO_T}none" >&6
+	else
+		echo "$as_me:$LINENO: result: ${CROSS_COMPILE}" >&5
+echo "${ECHO_T}${CROSS_COMPILE}" >&6
+	fi
+  fi
+ else
+    echo "$as_me:$LINENO: result: ${CROSS_COMPILE}" >&5
+echo "${ECHO_T}${CROSS_COMPILE}" >&6
+ fi
+
 
 
 
@@ -3630,12 +3635,12 @@ else
 		\$(LN_S) \$\$src;									\
 	    fi;												\
 	done;												\
-	\$(MAKE) -C $RTAI_LINUX_DIR									\
+	\$(MAKE) -C $RTEXT_LINUX_DIR									\
 		CROSS_COMPILE=\$(CROSS_COMPILE)								\
 		ARCH=\$(RTFW_TARGET_ARCH)								\
 		M=\"\`pwd\`\"										\
 		V=\$(V)											\
-		rtext_dir=\"${RTFW_RTAI_PREFIX}\"							\
+		rtext_dir=\"${RTFW_RTEXT_PREFIX}\"							\
 		top_srcdir=\"\`cd \$(top_srcdir) && pwd\`\"						\
 		top_builddir=\"\`cd \$(top_builddir) && pwd\`\"						\
 		srcdir=\"\`cd \$(srcdir) && pwd\`\"							\
@@ -3657,7 +3662,7 @@ else
    if test -e $RTEXT_LINUX_DIR/Module.symvers; then
 	mv $RTEXT_LINUX_DIR/Module.symvers $RTEXT_LINUX_DIR/Module.symvers.let_modpost_be_quiet
    fi
-   if test -e $RTAI_LINUX_DIR/vmlinux; then
+   if test -e $RTEXT_LINUX_DIR/vmlinux; then
 	mv $RTEXT_LINUX_DIR/vmlinux $RTFW_LINUX_DIR/vmlinux.let_modpost_be_quiet
    fi
 fi
@@ -3689,22 +3694,131 @@ CPPFLAGS="${ac_save_CPPFLAGS} ${RTEXT_KMOD_CFLAGS}"
 # headers, depending on the RTAI version which has been
 # identified. (rpm)
 
-BS_CHECK_KHEADERS(rtdm/rtdm.h rtdm/rtdm_driver.h,
-    ,
-    AC_MSG_ERROR([*** header not found or working, please check RTAI installation]),
+
+
+for ac_header in rtdm/rtdm.h rtdm/rtdm_driver.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
 #include <linux/kernel.h>
-    )
+
+
+#include <$ac_header>
+_ACEOF
+rm -f Makefile
+cat >Makefile <<_ACEOF
+EXTRA_CFLAGS += ${CFLAGS}
+EXTRA_CFLAGS += ${CPPFLAGS}
+obj-m += conftest.o
+_ACEOF
+rm -f conftest.$bs_kmodext conftest.o
+if { (eval echo "$as_me:$LINENO: \"$bs_kcompile > /dev/null\"") >&5
+  (eval $bs_kcompile > /dev/null) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.err conftest.$bs_kmodext conftest.o .conftest.o.d .conftest.o.cmd .conftest.ko.cmd .conftest.mod.o.cmd .tmp_versions/conftest.mod Makefile conftest.$ac_ext; rmdir .tmp_versions
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RTAI installation" >&5
+echo "$as_me: error: *** header not found or working, please check RTAI installation" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+done
+
 
 if test "${CONFIG_KBUILD}" = "y"; then  # building against linux-2.6
     case "${CONFIG_RTFW_RTEXT_VERSION}" in
         rtai-3x)
-            BS_CHECK_KHEADERS(rtai_sem.h rtai_malloc.h rtai_fifos.h,
-                ,
-                AC_MSG_ERROR([*** header not found or working, please check RTAI installation]),
+
+
+
+for ac_header in rtai_sem.h rtai_malloc.h rtai_fifos.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 
 #include <linux/kernel.h>
-                )
+
+
+#include <$ac_header>
+_ACEOF
+rm -f Makefile
+cat >Makefile <<_ACEOF
+EXTRA_CFLAGS += ${CFLAGS}
+EXTRA_CFLAGS += ${CPPFLAGS}
+obj-m += conftest.o
+_ACEOF
+rm -f conftest.$bs_kmodext conftest.o
+if { (eval echo "$as_me:$LINENO: \"$bs_kcompile > /dev/null\"") >&5
+  (eval $bs_kcompile > /dev/null) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  eval "$as_ac_Header=yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+eval "$as_ac_Header=no"
+fi
+rm -f conftest.err conftest.$bs_kmodext conftest.o .conftest.o.d .conftest.o.cmd .conftest.ko.cmd .conftest.mod.o.cmd .tmp_versions/conftest.mod Makefile conftest.$ac_ext; rmdir .tmp_versions
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: *** header not found or working, please check RTAI installation" >&5
+echo "$as_me: error: *** header not found or working, please check RTAI installation" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+done
+
             ;;
         xeno-2x)
             # nothing further to do
@@ -3895,8 +4009,8 @@ fi
 
 
 
-RTAI_KMOD_CFLAGS="-D__IN_RTFW__ $RTAI_KMOD_CFLAGS"
-RTAI_USER_CFLAGS="-D__IN_RTFW__ $RTAI_USER_CFLAGS"
+RTEXT_KMOD_CFLAGS="-D__IN_RTFW__ $RTEXT_KMOD_CFLAGS"
+RTEXT_USER_CFLAGS="-D__IN_RTFW__ $RTEXT_USER_CFLAGS"
 
 
 
@@ -4682,6 +4796,7 @@ s,@CONFIG_XENO_FALSE@,$CONFIG_XENO_FALSE,;t t
 s,@CONFIG_KBUILD_TRUE@,$CONFIG_KBUILD_TRUE,;t t
 s,@CONFIG_KBUILD_FALSE@,$CONFIG_KBUILD_FALSE,;t t
 s,@RTFW_TARGET_ARCH@,$RTFW_TARGET_ARCH,;t t
+s,@CROSS_COMPILE@,$CROSS_COMPILE,;t t
 s,@RTFW_MODULE_EXT@,$RTFW_MODULE_EXT,;t t
 s,@RTFW_KBUILD_ENV@,$RTFW_KBUILD_ENV,;t t
 s,@RTFW_KBUILD_CMD@,$RTFW_KBUILD_CMD,;t t
@@ -4689,8 +4804,8 @@ s,@RTFW_KBUILD_CLEAN@,$RTFW_KBUILD_CLEAN,;t t
 s,@RTFW_MODULE_DIR@,$RTFW_MODULE_DIR,;t t
 s,@CONFIG_RTFW_LXRT_TRUE@,$CONFIG_RTFW_LXRT_TRUE,;t t
 s,@CONFIG_RTFW_LXRT_FALSE@,$CONFIG_RTFW_LXRT_FALSE,;t t
-s,@RTAI_KMOD_CFLAGS@,$RTAI_KMOD_CFLAGS,;t t
-s,@RTAI_USER_CFLAGS@,$RTAI_USER_CFLAGS,;t t
+s,@RTEXT_KMOD_CFLAGS@,$RTEXT_KMOD_CFLAGS,;t t
+s,@RTEXT_USER_CFLAGS@,$RTEXT_USER_CFLAGS,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
